# Generated by Django 5.0.3 on 2024-04-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('marca', models.TextField(max_length=255)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
